project:
  type: website

website:
  title: "Third Year Labs - Ising Model"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Log of Work"  
        menu: 
          - text: "Log Overview"    
            href: Weekly-Log.qmd
          - text: "Week 1"
            href: week1.qmd
          - text: "Week 2"
            href: week2.qmd
          - text: "Week 3"
            href: week3.qmd
          - text: "Week 4"
            href: week4.qmd
          - text: "Week 5"
            href: week5.qmd
      - href: equ.qmd
        text: "Equations and Definitions"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

