---
title: "Week 6 Overview"
---

#### Main Activities: 
- Adapted Code in 2D to aid running efficiency
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * Whilst the 2D code produced in week 5 was running, it was very slow to produce the 300x300 cluster, 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; running with 20,000 steps. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I wrote the re-worked the code so that it would run in on block on Jupyter Notebook, as it seemed 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; this could decrease run times. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I also added a section to the code to produce a plot for each temperature output, visually displaying
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; the cluster shape and largest cluster size. 
<br>

- Continued with Report Writing 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * Further to my previous report writing done for this project, I started to focus on the theory,
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; methods, results and references sections. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * For the theory / methods section, I have used the equations compiled in week 5, along with an overview
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; of the coding methods used. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * For the referencing, I have used mybib.com to produce the citations, using Vancouver referring. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I have decided to include these in the report as plain references, rather than employing the 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; specific latex functionality, as previously that has been very unsuccessful. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * Once the code has complied, I then began by inputting the figures into latex, ensuring that the sizing
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; was uniform, orderly and optimal, from both readability and space-saving perspectives. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I then proceeded to write the captions for all of these graphs. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * Given the limited space, I selected the cluster graphs that contained the most information and best 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; assisted the narrative, and created a single plot to contain these 4 graphs. 


- Finalised the Lab Book 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * Given this is the last week of experiments, I decided to finalise the lab book. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I ensured that the weekly log was complete and up-to-date, that the equations page was functioning 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; and that the main page included relevant and completed information. 



#### Main Results: 
- Adapted the 2D code to aid running efficiency, ensuring large cluster sizes could be sustainably achieved.  
- Continued writing the report, focusing on the theory, methods, results and references sections. 
- Updated Lab Book to reflect to ensure that the weekly log was complete and the main page was detailed, ready for submission. 
