---
title: "Week 4 Overview"
---

#### Main Activities: 
- Upgraded the 2D Code
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * Looking at the output results produced in 2D last week, I decided to improve the quality of these.  
&nbsp;&nbsp;&nbsp;&nbsp; * I once again researched into the literature to see if there was a more sophisticated way to display
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; the data, as scatter graphs limit the clarity of the representation of the data. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I found that log plots showed a much more transparent representation of the data so made the relevant
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; graphs into log plots.   
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * Less needed changing for 1D - the only significant edit was how to graphically represent 1D shape. 

- Started to produce results 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I started to produce a few preliminary results, starting with 2D. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I began with a very small cluster size to confirm that the code was functioning correctly.  
&nbsp;&nbsp;&nbsp;&nbsp; * I then moved on to increasing the cluster size, noting that larger cluster sizes matched more closely 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  with the literature. A drawback to larger cluster sizes is the configuration time. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I decided it was better to get concrete results for 2D before moving onto other dimensions. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * To this end, I varied the temperature and cluster size to produce a series of results. 
- Updated Lab Book
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I put the information I had been collecting, such as the literature review notes, into the Lab book. 
<br>
&nbsp;&nbsp;&nbsp;&nbsp; * I also inputted my entries for weeks 1-3 that I had been storing on alternative software until now.  


#### Main Results: 
- Have functional code in 1D and 3D
- Produced a series of results and outputs for the 2D set-up
- Updated Lab Book
